### PR TITLE
Feature/html structure

### PR DESCRIPTION
**Pull request by JoshMallery**
# Description drawing

This feature adds the HTML Structure. It was put together by Eli and Josh. Please review and comment where necessary.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactor feature (non-breaking change that modifies existing work)
- [ ] Cosmetic changes (changes to layout or visuals in CSS file)

# How Has This Been Tested?

- [ ] console.log()
- [ ] dev tools
- [x] functionality check through web browser

# Checklist:

- [x] My code follows the style guidelines of this project (semicolons, indentation, naming conventions, etc..)
- [x] We have performed a self-review of our code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have deleted all comments/console.log() after functionality and understanding is final
- [x] I have added my other members are reviewers

### CODE REVIEW

**Review by mrlandino — CHANGES_REQUESTED** [review]
Hey Y'all,

This looks great. I think the only thing we need to add is the js script at the bottom of the HTML outside of the body to connect the HTML and JS files. 

Also, we can chat about this next meeting if need be, I normally name the containers for styling with "DIV" instead of "Section". This allows for better visual separation and knowing which HTML elements are strictly for styling purposes. Let me know your thoughts.

**Review by elleshadow — COMMENTED** [review]
Looking at the rubric, it looks like I misunderstood the "should not use Div" part, and missed where it had read that it was acceptable to use divs for style purposes. I have no objection to changing the ones you find appropriate to be divs, as long as Josh has no issue with it.

**Review by JoshMallery — COMMENTED** [review]
This looks good, thanks for reviewing the HTML file.

**Review by JoshMallery — COMMENTED** [review]
Ross it looks like you made the changes in a commit and they look good.

**Comment by elleshadow** [comment]
Reviewed HTML. No changes needed.

**Review by elleshadow — APPROVED** [review]
Reviewed changes to sections/divs. Looks good.

**Review by mrlandino — APPROVED** [review]
I approve of the changes made to section/div.

**Pull request merged**
